name: hellow-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Build-Application
        run: ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh